In [49]:
# Logistic Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
values = [[1,1],[1,0],[1,1],[1,1],[1,1],[1,1],[1,0],[1,0],[1,1],[0,0],[0,0],[0,0],[0,0],[0,0],[0,1],[0,0],[0,1],[0,0]]
column = ['iflas durumu','Şirket Büyüklüğü']
dataset = pd.DataFrame(values,columns=column)
X = dataset.iloc[:, 1].values
y = dataset.iloc[:, 0].values
dataset

    iflas durumu  Şirket Büyüklüğü
0              1                 1
1              1                 0
2              1                 1
3              1                 1
4              1                 1
5              1                 1
6              1                 0
7              1                 0
8              1                 1
9              0                 0
10             0                 0
11             0                 0
12             0                 0
13             0                 0
14             0                 1
15             0                 0
16             0                 1
17             0                 0

In [48]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train.reshape(-1, 1))
X_test = sc.transform(X_test.reshape(-1, 1))

# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train.reshape(-1, 1),y_train.reshape(-1, 1))

# Predicting the Test set results
y_pred = classifier.predict(X_test.reshape(-1, 1))

# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier2 = LogisticRegression(random_state = 0)
classifier2.fit(X.reshape(-1, 1),y.reshape(-1, 1))

# Predicting the Test set results
sample_pred = classifier.predict(np.ones((1,1)).reshape(-1, 1))
print("LogisticRegression.md dokumanında anlatıldığı gibi 1 yani büyük firma\
 özniteliği {} sınıfına atandı".format(sample_pred))
print("1 sınıfı iflas etmez \n0 Sınıfı iflas eder")

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("confusion matrisi:\n", cm)

LogisticRegression.md dokumanında anlatıldığı gibi 1 yani büyük firma özniteliği [1] sınıfına atandı
1 sınıfı iflas etmez
0 Sınıfı iflas eder
confusion matrisi:
 [[0 0]
 [2 0]]

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)